services:
  - name: president-engine
    type: web
    git:
      repository: github.com/yourusername/president-engine
      branch: main
      workdir: engine_py
    build:
      type: dockerfile
      dockerfile: Dockerfile
    instance:
      type: free
    ports:
      - port: 8000
        protocol: http
    health_checks:
      - path: /health
        port: 8000
        protocol: http
        initial_delay: 10
        timeout: 5
        interval: 30
        retries: 3
    scaling:
      min: 0  # Scale to zero when not in use
      max: 1  # Free tier limit
    env:
      - name: LOG_LEVEL
        value: info
      - name: MAX_ROOMS
        value: "500"
      - name: CORS_ORIGINS
        value: "*"
    # Uncomment and set if using Redis for persistence
    # secrets:
    #   - name: REDIS_URL
    #     value: "redis://username:password@host:port/database" 